### ISSUE TITLE
Extensions for system variables

### ISSUE THREAD

**Issue by spitzlbergerj** [Sickboy78/MMM-Homematic#1]
Hi sickboy78,
i have extended your MagicMirror module with the handling of system variables.

I could add all types except the value list. Since I'm a javascript beginner, I couldn't add the value list parameter to the values I'd get from the Homematic.  Maybe you can add this.

I packed my version into a fork. However, I would be happy if my variant could be included in your master branch.

Greetings from Germany
Sepp

**Comment by Sickboy78** [comment]
Hi Josef,

good idea!
I'm gonna have a look at it and I'll see, if I can get the value list running as well.
In any case, I'm gonna merge it into the master.

Thank you!
And Greetings from Erding to Oberschleißheim! :)
Sebastian

**Comment by spitzlbergerj** [comment]
Super, vielen Dank, das freut mich. Noch einen schönen Rest Sonntag

Viele Grüße Josef Spitzlberger

________________________________
Von: Sickboy78 <notifications@github.com>
Gesendet: Sonntag, 27. Januar 2019 16:59
An: Sickboy78/MMM-Homematic
Cc: josef@spitzlberger.de; Author
Betreff: Re: [Sickboy78/MMM-Homematic] Extensions for system variables (#1)


Hi Josef,

good idea!
I'm gonna have a look at it and I'll see, if I can get the value list running as well.
In any case, I'm gonna merge it into the master.

Thank you!
And Greetings from Erding to Oberschleißheim! :)
Sebastian

-

**Comment by Sickboy78** [comment]
Hi Josef,

I have merged your additions, thanks for the contribution!
I have looked into the value list issue and it's not as easy, since the state.cgi of the XML-API only delivers the current index, but not the value or values.
So I have to integrate a call to sysvar.cgi for the values in the future.
And I'd like to extend 'sysvar_string_warn' to 'sysvar_string_warn_empty' and 'sysvar_string_warn_not_empty', if you don't mind?

Best Regards
Sebastian

**Comment by spitzlbergerj** [comment]
Hi, Sebastian,
Thank you very much. I'm very happy about that. 
I had already seen that the value list would be difficult. That's why I didn't look at it any further. But at the moment I don't need it either.  But I wanted to have addressed all variable types.
Then I noticed something else. You use threshold as string variable, I used it as integer variable, because I only looked at the description and not at your code. In the code I later saw that you used it as string. We should adjust that.
And of course you can change the string warning as you see fit.

I am also a github newbie. Should/must/can I then close my fork again, or does this "happen" automatically?

Many thanks again
greetings
Sepp

**Comment by Sickboy78** [comment]
Hi Sepp,

I added support for the value list.
And I changed the type of threshold and precision to number.

Regarding your question, I think you can delete your fork.
Normally you would have created a Pull Request on my repo, which would have given you a button to delete your fork after the merge is done.
But since I created the Pull Request myself, I can not delete your fork, so you have to go under settings into the "danger zone". :) There you can delete or archive your fork.

Best Regards
Sebastian

**Comment by spitzlbergerj** [comment]
Thank you, Sebastian,

That was very fast. Then I will delete my fork myself now and in the future I will initiate a pull request. I must become still something better in the operation of git ;-)
Greetings
Sepp
