### ISSUE TITLE
APIXML Update and Module don't work

### ISSUE THREAD

**Issue by oekomat** [Sickboy78/MMM-Homematic#13]
Hello Sebasttian,

in my config file I have my registered Token pushed. Looks like:

`config:	{
ccuHost: 'IP from CCU',
ccuXmlApiTokenId: 'Token from tokenlist.cgi',
datapoints:
	[			{
					id: "8673",
					name: "Fenster Bad",
					type: "window_warn_open",
				warnOnly: "true",
					warn_only: "true",
					warnColor: "red"
				},`

But my Module show "loading".
I have this case with apixml 2.1 and 2.2

Until the update from apixml it works fine

Can you help me please?

**Comment by oekomat** [comment]
further information, my mirror log shows:

[14.11.2023 15:40.56.475] [LOG]   Error: Could not get data from Homematic XML-API because:
[14.11.2023 15:40.56.475] [LOG]   Homematic XML-API Request returned status 404


But the token must be ok, because

http://[IP CCU]/addons/xmlapi/devicelist.cgi?sid=[Token] shows the right data site.

**Comment by Sickboy78** [comment]
Hi,

if the token is invalid, the error would say:
"_[LOG]   Homematic XML-API Request returned 'not authenticated'. Try setting a ccuXmlApiTokenId in your module config._"

But 404 means page not found. Strange.
Have you restarted your CCU since the XML-API Update? If not, please try that first.
If this does not help, try setting the https protocol: ccuProtocol: "https://".
If this also does not help, please execute the following curl statement on the mashine where MagicMirror is running and copy me the output here:
`curl -v http://[IP CCU]/addons/xmlapi/devicelist.cgi`
and
`curl -vk https://[IP CCU]/addons/xmlapi/devicelist.cgi`

Best Regards

**Comment by Sickboy78** [comment]
Since there was no feedback for over 3 weeks, I guess the issue is solved.
